In [1]:
import pandas as pd
import duckdb

from juptils import pretty
from juptils import lefty

# Supplier queries

In [2]:
monthly_sales = pd.read_csv("./csv/monthly-sales.csv")
#monthly_sales

## Yearly Sales

In [12]:
#  format('{:t,.2f}', your_float64_col) 
#  works '{:t,}' 
#  .pretty(int_col="ytd_amt")
#  SUM(month_amt) AS ytd_amt


duckdb.query("""
SELECT 
    SUBSTR(month, 1, 4) AS year, 
    supplier, 
    lpad(format('{:t,}', SUM(month_amt)), 10, ' ') AS ytd_amt
FROM monthly_sales
GROUP BY year, supplier
ORDER BY year, supplier
""").df()#.lefty()

   year      SUPPLIER     ytd_amt
0  2023  nippon-metal   9,360,700
1  2023      us-steel   9,675,200
2  2024  nippon-metal   9,489,700
3  2024      us-steel   8,797,300
4  2025  nippon-metal  11,298,600
5  2025      us-steel  13,043,700
6  2026  nippon-metal   1,153,000
7  2026      us-steel     306,300

# Quarterly Sales

In [4]:
duckdb.query("""
SELECT 
    SUBSTR(month, 1, 4) || '-Q' || 
    CAST(CEIL(CAST(SUBSTR(month, 6, 2) AS INT64) / 3.0) AS INT64) AS quarter,
    supplier,
    SUM(month_amt) AS quarter_total
FROM monthly_sales
GROUP BY quarter, supplier
ORDER BY quarter, supplier
""").df()

    quarter      SUPPLIER  quarter_total
0   2023-Q1  nippon-metal       709400.0
1   2023-Q1      us-steel       569200.0
2   2023-Q2  nippon-metal      2388200.0
3   2023-Q2      us-steel      3766900.0
4   2023-Q3  nippon-metal      3842200.0
5   2023-Q3      us-steel      3007500.0
6   2023-Q4  nippon-metal      2420900.0
7   2023-Q4      us-steel      2331600.0
8   2024-Q1  nippon-metal      3053200.0
9   2024-Q1      us-steel      2446100.0
10  2024-Q2  nippon-metal      2534800.0
11  2024-Q2      us-steel      1836200.0
12  2024-Q3  nippon-metal      1386500.0
13  2024-Q3      us-steel      1943300.0
14  2024-Q4  nippon-metal      2515200.0
15  2024-Q4      us-steel      2571700.0
16  2025-Q1  nippon-metal      3055400.0
17  2025-Q1      us-steel      2987300.0
18  2025-Q2  nippon-metal      2960500.0
19  2025-Q2      us-steel      3166800.0
20  2025-Q3  nippon-metal      2853800.0
21  2025-Q3      us-steel      4044900.0
22  2025-Q4  nippon-metal      2428900.0
23  2025-Q4      us-steel      2844700.0
24  2026-Q1  nippon-metal      1153000.0
25  2026-Q1      us-steel       306300.0